# Generated by Django 6.0.1 on 2026-01-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
