# Generated by Django 6.0.1 on 2026-01-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_customer_otp_customer_otp_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
