# Generated by Django 6.0.1 on 2026-01-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image1",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image2",
        ),
    ]
