# Generated by Django 6.0.1 on 2026-01-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
