"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-42$*i&gx$j*!-1y@y0)qoq8vs12$38k6e_d5n8dlde-3a^_a9z"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# ADD THIS - Telegram Bot Configuration
import os
TELEGRAM_BOT_ID = "5656155274"
TELEGRAM_BOT_TOKEN = "8516971237:AAGTsm-OTRg2Q35e7COB4ljQnlP65-EqJAI"  # Get this from @BotFather


# Application definition

INSTALLED_APPS = [
    "user",
    "customer",
    "product",
    "category",
    "subscription",
    "rest_framework",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'corsheaders',
    
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

#CORS
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:8001',
    'http://localhost:5500',
    'http://127.0.0.1:5500',
    'http://127.0.0.1:8000',
    "http://localhost:4200",
]

CORS_ALLOW_CREDENTIALS = True



# """
# Django settings for myproject project.

# Generated by 'django-admin startproject' using Django 6.0.

# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
# """

# from pathlib import Path
# import os

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-42$*i&gx$j*!-1y@y0)qoq8vs12$38k6e_d5n8dlde-3a^_a9z"

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     "user",
#     #"customer",
#     #"product",
#     #"categories",
#     "rest_framework",
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     'corsheaders',
    
# ]

# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
# ]

# ROOT_URLCONF = "myproject.urls"

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = "myproject.wsgi.application"


# # Database
# # https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = "static/"

# # Default primary key field type
# # https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# #CORS
# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',
#     'http://localhost:8001',
#     'http://localhost:5500',
#     'http://127.0.0.1:5500',
#     'http://127.0.0.1:8000',
#     "http://localhost:4200",
# ]

# CORS_ALLOW_CREDENTIALS = True

# # ============================================================================
# # TELEGRAM BOT CONFIGURATION (ADD THIS SECTION)
# # ============================================================================

# # Telegram Bot Token - Get this from @BotFather on Telegram
# # IMPORTANT: Replace with your actual bot token
# # TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', 'YOUR_BOT_TOKEN_HERE')

# # Alternative: You can hardcode it for development (NOT RECOMMENDED for production)
# TELEGRAM_BOT_TOKEN = '8579173598:AAH7g6bRwrwngyJNdKvYqgYpNiF_aiIL2zk'


# # ============================================================================
# # CACHE CONFIGURATION (Required for OTP storage)
# # ============================================================================

# # For Development: Use Local Memory Cache
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'unique-snowflake',
#         'TIMEOUT': 600,  # Default timeout of 10 minutes
#         'OPTIONS': {
#             'MAX_ENTRIES': 1000
#         }
#     }
# }

# # For Production: Use Redis Cache (Recommended)
# # Uncomment below and install redis: pip install redis django-redis
# # CACHES = {
# #     'default': {
# #         'BACKEND': 'django_redis.cache.RedisCache',
# #         'LOCATION': 'redis://127.0.0.1:6379/1',
# #         'OPTIONS': {
# #             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
# #             'CONNECTION_POOL_KWARGS': {'max_connections': 50}
# #         }
# #     }
# # }


# # ============================================================================
# # REST FRAMEWORK CONFIGURATION (Optional but recommended)
# # ============================================================================

# REST_FRAMEWORK = {
#     'DEFAULT_RENDERER_CLASSES': [
#         'rest_framework.renderers.JSONRenderer',
#     ],
#     'DEFAULT_PARSER_CLASSES': [
#         'rest_framework.parsers.JSONParser',
#     ],
# }


# # ============================================================================
# # SECURITY SETTINGS (Optional but recommended for production)
# # ============================================================================

# # CSRF Settings - if you're having CSRF issues with your frontend
# CSRF_TRUSTED_ORIGINS = [
#     'http://localhost:3000',
#     'http://localhost:8001',
#     'http://localhost:5500',
#     'http://127.0.0.1:5500',
#     'http://127.0.0.1:8000',
#     'http://localhost:4200',
# ]

# # For development, you might want to disable CSRF on API endpoints
# # Add this to your API views: @csrf_exempt decorator
# # Or use SessionAuthentication in REST_FRAMEWORK settings