# Generated by Django 6.0.1 on 2026-01-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_telegram_chat_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telegram_chat_id",
        ),
    ]
