# Generated by Django 6.0.1 on 2026-01-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_telegram_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=20),
        ),
    ]
